// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ParksAPI.Models;

namespace ParksAPI.Migrations
{
    [DbContext(typeof(ParksAPIContext))]
    [Migration("20210611222935_SeedData")]
    partial class SeedData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("ParksAPI.Models.Park", b =>
                {
                    b.Property<int>("ParkId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Location")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Name")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Review")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("ParkId");

                    b.ToTable("Parks");

                    b.HasData(
                        new
                        {
                            ParkId = 1,
                            Location = "Saddle Mountain State Park Rd, Seaside, OR, 97138",
                            Name = "Saddle Mountain",
                            Review = "This park is open year round, but is only open for day use at the moment. Make sure to bring your own water and hand sanitizer, if need be. The hike can be difficult, but I will say the view is worth the work put in! You can see the ocean horizon at the very top!"
                        },
                        new
                        {
                            ParkId = 2,
                            Location = "East Historic Columbia River, Bridal Veil, OR, 97010",
                            Name = "Angel's Rest Trailhead",
                            Review = "This hike can be pretty intensive, but totally worth the view, at least from the photos I've seen. Make sure you're endurance is up for this hike, or you might have to turn back like me."
                        },
                        new
                        {
                            ParkId = 3,
                            Location = "20024 Silver Falls Hwy SE, Sublimity, OR, 97385",
                            Name = "Silver Falls",
                            Review = "Some trails have been closed due to the recent wildfires, but there are still some trails open at the moment. The many falls around are quite beautiful and refreshing. Some of the trails are quite narrow, so if you don't feel comfortable around many others, wear a mask and go during a time it's not so busy."
                        },
                        new
                        {
                            ParkId = 4,
                            Location = "Wallowa Lake State Park, Joseph, OR, 97846",
                            Name = "Wallowa Lake",
                            Review = "Lots of camping and activities around and the lake is gorgeous! It is located in Easter Oregon, but worth the drive! The mountains surrounding the lake are breathtaking too."
                        },
                        new
                        {
                            ParkId = 5,
                            Location = "Crater Lake National Park, Rim Dr, OR, 97604",
                            Name = "Crater Lake",
                            Review = "This is a must see Park! The water is so blue and beautiful! There are little critters everywhere too. Make sure you check the weather conditions before you go, the north entrance might be snowed in if it's too cold. Overall, lovely place!"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
